"""
Application Constants - Core Configuration Values
"""

# System Limits
DEFAULT_MAX_ITEMS = 10000
DEFAULT_BATCH_SIZE = 100
DEFAULT_TIMEOUT = 30
MAX_RETRIES = 5

# Compliance Constants
DFARS_RETENTION_DAYS = 2555  # 7 years
NASA_MAX_FUNCTION_LENGTH = 60
NASA_MIN_ASSERTION_DENSITY = 2.0
GOD_OBJECT_METHOD_THRESHOLD = 15
CONNASCENCE_SEVERITY_THRESHOLD = 3

# Network Constants
DEFAULT_PORT = 8080
HTTPS_PORT = 443
HTTP_PORT = 80
LOCALHOST = "127.0.0.1"

# Quality Thresholds
MIN_TEST_COVERAGE = 80.0
MIN_DOCUMENTATION_COVERAGE = 90.0
MAX_CYCLOMATIC_COMPLEXITY = 10
MAX_COGNITIVE_COMPLEXITY = 15
MAX_DUPLICATION_PERCENTAGE = 5.0
QUALITY_GATE_MINIMUM_PASS_RATE = 85.0  # Minimum pass rate for quality gates
MAXIMUM_RETRY_ATTEMPTS = 3  # Maximum retry attempts for operations

# Performance Constants
CACHE_SIZE_MB = 100
MAX_CONCURRENT_REQUESTS = 1000
CONNECTION_POOL_SIZE = 20
WORKER_THREAD_COUNT = 4

# Status Codes
SUCCESS = 0
FAILURE = 1
ERROR = -1
WARNING = 2
INFO = 3

# File System Constants
MAX_FILE_SIZE_MB = 100
MAX_PATH_LENGTH = 260
DEFAULT_ENCODING = "utf-8"

# Analysis Constants
MIN_CONFIDENCE_SCORE = 0.75
HIGH_SEVERITY_THRESHOLD = 0.8
CRITICAL_SEVERITY_THRESHOLD = 0.95

# Export meaningful constants
__all__ = [
    # Limits
    'DEFAULT_MAX_ITEMS', 'DEFAULT_BATCH_SIZE', 'DEFAULT_TIMEOUT', 'MAX_RETRIES',

    # Compliance
    'DFARS_RETENTION_DAYS', 'NASA_MAX_FUNCTION_LENGTH',
    'NASA_MIN_ASSERTION_DENSITY', 'GOD_OBJECT_METHOD_THRESHOLD',
    'CONNASCENCE_SEVERITY_THRESHOLD',

    # Network
    'DEFAULT_PORT', 'HTTPS_PORT', 'HTTP_PORT', 'LOCALHOST',

    # Quality Thresholds
    'MIN_TEST_COVERAGE', 'MIN_DOCUMENTATION_COVERAGE',
    'MAX_CYCLOMATIC_COMPLEXITY', 'MAX_COGNITIVE_COMPLEXITY',
    'MAX_DUPLICATION_PERCENTAGE',

    # Performance
    'CACHE_SIZE_MB', 'MAX_CONCURRENT_REQUESTS',
    'CONNECTION_POOL_SIZE', 'WORKER_THREAD_COUNT',

    # Status Codes
    'SUCCESS', 'FAILURE', 'ERROR', 'WARNING', 'INFO',

    # File System
    'MAX_FILE_SIZE_MB', 'MAX_PATH_LENGTH', 'DEFAULT_ENCODING',

    # Analysis Thresholds
    'MIN_CONFIDENCE_SCORE', 'HIGH_SEVERITY_THRESHOLD',
    'CRITICAL_SEVERITY_THRESHOLD'
]